services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: >
      sh -c "php artisan migrate --force &&
             apache2-foreground"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laraveluser
      POSTGRES_PASSWORD: laravelpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - "5432:5432"

networks:
  laravel:

volumes:
  pgdata:
